### ISSUE TITLE
[!] Unknown installation options: warn_for_unused_master_specs_repo.

### ISSUE THREAD

**Issue by amatig** [adobe/aepsdk-places-ios#24]
### Expected Behaviour

It should be able to compile the libs

### Actual Behaviour

I doesn't install the pod and complete the make archive, it gives and error

[!] Unknown installation options: warn_for_unused_master_specs_repo

#### Steps to Reproduce

Run "make archive"

#### Platform and Version

Montrey 12.4

**Comment by sbenedicadb** [comment]
fixed in 3.0.2
